//
//  ArticlesScreenViewController.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticlesScreenViewController: UITableViewController {

    struct CellModel: Hashable {
        let id = UUID()
        let article: Article
        
        // enough for now
        static func == (lhs: ArticlesScreenViewController.CellModel, rhs: ArticlesScreenViewController.CellModel) -> Bool {
            lhs.id == rhs.id
        }
        func hash(into hasher: inout Hasher) {
            hasher.combine(id)
        }
    }
    
    lazy var datasource = UITableViewDiffableDataSource<Int, CellModel>(tableView: tableView) { tableView, indexPath, itemIdentifier in
        let cell = tableView.dequeueReusableCell(withIdentifier: "ArticleTableViewCell", for: indexPath) as! ArticleTableViewCell
        cell.article = itemIdentifier.article
        cell.accessoryType = UITableViewCell.AccessoryType.disclosureIndicator
        
        TestUtils.FlagCellInTable(table: tableView, cell: cell, indexPath: indexPath)
        return cell
    }
    
    let activityIndicatorView = UIActivityIndicatorView(style: .medium)
    
    // MARK: - Public properties -

    var presenter: ArticlesScreenPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title = "NYT Most Viewed"
        
        // move to build function...
        TestUtils.FlagTableInClass(table: tableView, className: "ArticlesController")
        tableView.tableHeaderView = activityIndicatorView
        tableView.register(
            ArticleTableViewCell.self,
            forCellReuseIdentifier: ArticleTableViewCell.identifier
        )

        presenter.viewLoaded()
    }

    override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let percentage = scrollView.contentOffset.y / scrollView.contentSize.height
        // load next page when we reach 70% of scroll
        if percentage > 0.7 {
            presenter.didReachEnd()
        }
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        if let model = self.datasource.itemIdentifier(for: indexPath) {
            self.presenter.tapped(article: model.article)
        }
    }
}

// MARK: - Extensions -

extension ArticlesScreenViewController: ArticlesScreenViewInterface {
    func loading() {
        activityIndicatorView.startAnimating()
    }
    func setArticles(articles: [Article]) {
        activityIndicatorView.stopAnimating()
        self.title = "NYT Most Viewed (\(articles.count))"
        
        let cellModels = articles.map { CellModel(article: $0) }
        
        var snapshot = NSDiffableDataSourceSnapshot<Int, CellModel>()
        snapshot.appendSections([1])
        snapshot.appendItems(cellModels)
        datasource.apply(snapshot, animatingDifferences: false)
    }
    func error(_ error: Error) {
        let alertController = UIAlertController(
            title: "Something Happened !",
            message: "\(error)",
            preferredStyle: .alert)
        let dismissAction = UIAlertAction(title: "Okay", style: .default) { (action:UIAlertAction) in
            alertController.dismiss(animated: true, completion: nil)
        }
        alertController.addAction(dismissAction)
        self.present(alertController, animated: true, completion: nil)
    }
}
