//
//  ArticlesScreenInterfaces.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine

protocol ArticlesScreenWireframeInterface: WireframeInterface {
    func routeToArticleDetails(article: Article)
}

protocol ArticlesScreenViewInterface: ViewInterface {
    func setArticles(articles: [Article])
    func loading()
    func error(_ error: Error)
}

protocol ArticlesScreenPresenterInterface: PresenterInterface {
    func viewLoaded()
    func didReachEnd()
    func tapped(article: Article) // this could be an id only
}

protocol ArticlesScreenInteractorInterface: InteractorInterface {
    var articlesResults: PassthroughSubject<[Article], Error> { get }

    func nextPage()
}
