//
//  ArticlesScreenInteractor.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Combine
final class ArticlesScreenInteractor {
    
    private var isLoading: Bool = false
    // this can be moved to a seperate pagination service
    private var currentPage: Int = -1
    // injected repository
    public var articlesRepository: ArticleRepositoryInterface!
    
    public var articlesResults = PassthroughSubject<[Article], Error>()
}

// MARK: - Extensions -

extension ArticlesScreenInteractor: ArticlesScreenInteractorInterface {
    func nextPage() {
        guard !isLoading else { return }
        isLoading = true
        currentPage = currentPage + 1
        
        articlesRepository.fetchMostPopular { [weak self] (result) in
            self?.isLoading = false
            
            switch result {
            case .success(let articles):
                self?.articlesResults.send(articles)
            case .failure(let error):
                self?.articlesResults.send(completion: .failure(error))
            }
        }
    }
}
