//
//  ArticlesScreenWireframe.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticlesScreenWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ArticlesScreenViewController()
        super.init(viewController: moduleViewController)

        let interactor = ArticlesScreenInteractor()
        interactor.articlesRepository = LiveArticleRepository() // replace this with a builder
        
        let presenter = ArticlesScreenPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ArticlesScreenWireframe: ArticlesScreenWireframeInterface {
    func routeToArticleDetails(article: Article) {
        let wireframe = ArticleDetailWireframe(article: article)
        self.navigationController?.pushViewController(wireframe.viewController, animated: true)
    }
}
