//
//  ArticleDetailWireframe.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(article: Article) {
        let moduleViewController = ArticleDetailViewController()
        super.init(viewController: moduleViewController)

        let presenter = ArticleDetailPresenter(view: moduleViewController, wireframe: self)
        presenter.article = article
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ArticleDetailWireframe: ArticleDetailWireframeInterface {
}
