//
//  ArticleDetailInterfaces.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ArticleDetailWireframeInterface: WireframeInterface {
}

protocol ArticleDetailViewInterface: ViewInterface {
    func article(_ article: Article)
}

protocol ArticleDetailPresenterInterface: PresenterInterface {
    func viewLoaded()
}
