//
//  ArticleDetailPresenter.swift
//  TestApp
//
//  Created by Georges on 12/5/20.
//  Copyright (c) 2020 Xeronium. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ArticleDetailPresenter {
    
    var article: Article!
    
    // MARK: - Private properties -

    private unowned let view: ArticleDetailViewInterface
    private let wireframe: ArticleDetailWireframeInterface

    // MARK: - Lifecycle -

    init(view: ArticleDetailViewInterface, wireframe: ArticleDetailWireframeInterface) {
        self.view = view
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension ArticleDetailPresenter: ArticleDetailPresenterInterface {
    func viewLoaded() {
        self.view.article(article)
    }
}
